import { NextPage } from 'next';
import { HeaderBar } from './header';
import Head from 'next/head';

type Props = {
  children?: React.ReactNode;
  // home?: boolean;
};

const Layout: NextPage<Props> = ({ children }) => {
  return (
    <div className="flex flex-col h-screen font-mono text-base">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderBar />
      <main className="flex-1 w-full px-3 py-4 mx-auto sm:py-6 sm:px-6 lg:px-8">
        <div className="h-full mx-auto max-w-7xl">{children}</div>
      </main>
    </div>
  );
};

export default Layout;
